"""Five mock patient profiles for simulator and demo."""
from typing import Any

PATIENT_PROFILES: dict[str, dict[str, Any]] = {
    "PT-0001": {
        "name": "Rajesh Kumar",
        "age": 62,
        "gender": "Male",
        "scenario": "STABLE",
        "ward": "General Ward A",
        "bed": "12B",
        "conditions": [
            {"code": "I10", "name": "Hypertension"},
            {"code": "E11", "name": "Type 2 Diabetes"},
        ],
        "medications": [
            {"name": "Metformin", "dose": "500mg", "frequency": "BD"},
            {"name": "Amlodipine", "dose": "5mg", "frequency": "OD"},
        ],
        "baseline_hr": 88,
        "baseline_spo2": 96,
        "baseline_temp": 37.0,
        "trajectory": "flat_with_noise",
        "expected_outcome": "STABLE — no alert ever",
    },
    "PT-0002": {
        "name": "Priya Sharma",
        "age": 34,
        "gender": "Female",
        "scenario": "TRAJECTORY_ACCELERATION",
        "ward": "Surgical Ward B",
        "bed": "4A",
        "conditions": [
            {"code": "Z48.8", "name": "Post-appendectomy Day 2"},
            {"code": "E11", "name": "Type 2 Diabetes"},
        ],
        "medications": [
            {"name": "Cefazolin", "dose": "1g IV", "frequency": "Q8H"},
            {"name": "Metformin", "dose": "500mg", "frequency": "BD"},
            {"name": "Paracetamol", "dose": "500mg", "frequency": "Q6H PRN"},
        ],
        "baseline_hr": 82,
        "baseline_spo2": 97,
        "baseline_temp": 37.0,
        "trajectory": "exponential_acceleration",
        "expected_outcome": "SYNERA_STATE fired at ~103 BPM (8-15 min before threshold)",
    },
    "PT-0003": {
        "name": "Arjun Mehta",
        "age": 28,
        "gender": "Male",
        "scenario": "EXERTION_FALSE_POSITIVE",
        "ward": "General Ward A",
        "bed": "7C",
        "conditions": [],
        "medications": [],
        "baseline_hr": 68,
        "baseline_spo2": 99,
        "baseline_temp": 37.0,
        "trajectory": "exertion_spike",
        "expected_outcome": "EXERTION_LOGGED — NO alert. Rule B catches this.",
    },
    "PT-0004": {
        "name": "Fatima Begum",
        "age": 71,
        "gender": "Female",
        "scenario": "GLITCH_SPIKE",
        "ward": "ICU Step-Down",
        "bed": "2",
        "conditions": [
            {"code": "J44", "name": "COPD"},
            {"code": "I48", "name": "Atrial Fibrillation"},
        ],
        "medications": [
            {"name": "Warfarin", "dose": "5mg", "frequency": "OD"},
            {"name": "Salbutamol", "dose": "100mcg inhaler", "frequency": "PRN"},
            {"name": "Digoxin", "dose": "0.25mg", "frequency": "OD"},
        ],
        "baseline_hr": 79,
        "baseline_spo2": 94,
        "baseline_temp": 37.0,
        "trajectory": "glitch_spike",
        "glitch_value": 228,
        "glitch_index": 3,
        "expected_outcome": "ARTIFACT — packet silently discarded.",
    },
    "PT-0005": {
        "name": "Suresh Patel",
        "age": 55,
        "gender": "Male",
        "scenario": "SLOW_DRIFT_WATCH",
        "ward": "General Ward C",
        "bed": "9A",
        "conditions": [
            {"code": "I10", "name": "Hypertension"},
            {"code": "N18.3", "name": "CKD Stage 3"},
        ],
        "medications": [
            {"name": "Losartan", "dose": "50mg", "frequency": "OD"},
            {"name": "Furosemide", "dose": "40mg", "frequency": "OD"},
        ],
        "baseline_hr": 76,
        "baseline_spo2": 97,
        "baseline_temp": 37.0,
        "trajectory": "slow_linear_drift",
        "expected_outcome": "WATCH tier — deviation triggered, no acceleration, no RAG call",
    },
}
