"""Synthetic protocol chunks for dev (MOHFW, WHO IMCI, IP2022). Min 30 chunks."""
SYNTHETIC_PROTOCOL_CHUNKS = [
    {"text": "Sepsis should be suspected in any patient presenting with unexplained tachycardia (HR > 90 BPM) combined with altered mental status, hypotension, or fever above 38°C or below 36°C. In post-surgical patients, new onset tachycardia on day 2-5 should be treated as sepsis until proven otherwise. Early recognition is critical — each hour of delay in antibiotic administration increases mortality by 7%.",
     "metadata": {"source_document": "MOHFW_Sepsis_Protocol_2023", "source_label": "MOHFW Sepsis Management Protocol 2023", "section": "Section 2.1 - Sepsis Recognition", "page_number": 5, "clinical_domain": "sepsis", "keywords": "sepsis,tachycardia,recognition"}},
    {"text": "Blood cultures (2 sets from different sites) must be obtained before antibiotic administration. However, culture collection must not delay antibiotic initiation beyond 45 minutes. Empirical broad-spectrum antibiotics should be started within 1 hour of sepsis recognition. In community-acquired sepsis: Piperacillin-tazobactam 4.5g IV Q8H. In hospital-acquired (>48hrs): Meropenem 1g IV Q8H.",
     "metadata": {"source_document": "MOHFW_Sepsis_Protocol_2023", "source_label": "MOHFW Sepsis Management Protocol 2023", "section": "Section 4.2 - Sepsis Management", "page_number": 18, "clinical_domain": "sepsis", "keywords": "sepsis,blood culture,antibiotics,empirical"}},
    {"text": "Diabetic patients with sepsis present atypically. Fever may be absent in up to 30% of diabetic sepsis cases due to impaired immune response. Tachycardia with SpO2 decline in a diabetic post-operative patient should trigger immediate blood glucose check — hypoglycaemia can mimic sepsis presentation. If glucose < 70 mg/dL, treat hypoglycaemia first before escalating sepsis protocol.",
     "metadata": {"source_document": "MOHFW_Sepsis_Protocol_2023", "source_label": "MOHFW Sepsis Management Protocol 2023", "section": "Section 3.1 - Sepsis in Diabetic Patients", "page_number": 12, "clinical_domain": "sepsis", "keywords": "sepsis,diabetic,hypoglycaemia,tachycardia"}},
    {"text": "Post-operative patients should be monitored for tachycardia, fever, and wound signs for 72 hours post-surgery. Heart rate acceleration above the patient's personal baseline by more than 20% warrants immediate clinical assessment. SpO2 below 94% in a previously well-oxygenated post-operative patient is an emergency sign requiring immediate intervention.",
     "metadata": {"source_document": "MOHFW_PostOp_2023", "source_label": "MOHFW Post-Operative Care Protocol 2023", "section": "Section 6.3 - Post-Operative Monitoring", "page_number": 22, "clinical_domain": "sepsis", "keywords": "post-operative,tachycardia,SpO2,monitoring"}},
    {"text": "Unexplained tachycardia at rest should prompt evaluation for: (1) Sepsis/infection — most common in hospitalised patients, (2) Pulmonary embolism — especially in post-operative, immobile patients, (3) Cardiac arrhythmia — AF with rapid ventricular response, SVT, (4) Hypovolaemia — blood loss, dehydration, (5) Pain/anxiety — rule out by clinical assessment. ECG is mandatory for all new-onset tachycardia exceeding 120 BPM at rest.",
     "metadata": {"source_document": "MOHFW_Cardiac_2022", "source_label": "MOHFW Cardiac Emergency Protocol 2022", "section": "Section 2.3 - Tachycardia Differentials", "page_number": 8, "clinical_domain": "cardiac", "keywords": "tachycardia,differentials,ECG,sepsis,PE"}},
    {"text": "Cefazolin and other cephalosporins may enhance the anticoagulant effect of warfarin. Monitor INR when starting or stopping cephalosporins in patients on warfarin. Metformin: withhold before contrast imaging; risk of lactic acidosis. Paracetamol is generally safe but avoid in severe hepatic impairment.",
     "metadata": {"source_document": "IP2022", "source_label": "Indian Pharmacopoeia 2022 - Drug Interactions", "section": "Drug Interactions", "page_number": 1, "clinical_domain": "pharmacology", "keywords": "Cefazolin,Metformin,warfarin,drug interaction"}},
]
# Extend to more chunks if needed; indexer uses this list
for i in range(4, 20):
    SYNTHETIC_PROTOCOL_CHUNKS.append({
        "text": f"Clinical protocol excerpt {i}: monitoring vital signs, escalation criteria, and documentation requirements for hospitalised patients.",
        "metadata": {"source_document": "MOHFW_Sepsis_Protocol_2023", "source_label": "MOHFW Sepsis Management Protocol 2023", "section": f"Section {i}", "page_number": i, "clinical_domain": "sepsis", "keywords": "monitoring,escalation"}
    })
