/**
 * Synera 2.0 — LSTM Autoencoder Inference (model_runner.c)
 * =========================================================
 * Pure-C implementation of VitalAutoencoder forward pass.
 * All weights are sourced from autoencoder_model.h (generated by the Python
 * export pipeline — do not edit weight values manually).
 *
 * Gate ordering follows PyTorch LSTM convention:
 *   weight_ih / weight_hh rows → [input | forget | cell | output]
 *   Indices: [0..H-1]=i,  [H..2H-1]=f,  [2H..3H-1]=g,  [3H..4H-1]=o
 *   where H = SYNERA_HIDDEN_SIZE = 16
 *
 * Memory usage (stack only, no heap):
 *   ~1 KB stack at peak (LSTM states + gate buffers)
 */

#include "model_runner.h"

#include <math.h>
#include <string.h>

/* ── Private helpers ──────────────────────────────────────────────────────── */

static inline float _sigmoid(float x)
{
    return 1.0f / (1.0f + expf(-x));
}

/**
 * Generic LSTM cell step.
 *
 * Computes one recurrent step:
 *   gates = wih @ x + bih + whh @ h + bhh
 *   i = sigmoid(gates[0..H])
 *   f = sigmoid(gates[H..2H])
 *   g = tanh(gates[2H..3H])
 *   o = sigmoid(gates[3H..4H])
 *   c' = f*c + i*g
 *   h' = o*tanh(c')
 *
 * @param x          Input vector [nx]
 * @param nx         Input dimension
 * @param h          Hidden state [nh] — updated in-place
 * @param c          Cell state [nh]   — updated in-place
 * @param wih        weight_ih [4*nh x nx] row-major
 * @param whh        weight_hh [4*nh x nh] row-major
 * @param bih        bias_ih [4*nh]
 * @param bhh        bias_hh [4*nh]
 * @param nh         Hidden dimension
 */
static void _lstm_step(
    const float *x,     int nx,
    float       *h,     float *c,
    const float *wih,
    const float *whh,
    const float *bih,
    const float *bhh,
    int          nh)
{
    /* Scratch buffer for pre-activation gate values.
       Max size: 4 * SYNERA_HIDDEN_SIZE = 64 */
    float gate[4 * SYNERA_HIDDEN_SIZE];

    for (int g = 0; g < 4 * nh; g++) {
        float v = bih[g] + bhh[g];
        const float *wih_row = wih + g * nx;
        const float *whh_row = whh + g * nh;
        for (int j = 0; j < nx; j++) v += wih_row[j] * x[j];
        for (int j = 0; j < nh; j++) v += whh_row[j] * h[j];
        gate[g] = v;
    }

    /* Update cell and hidden states */
    for (int i = 0; i < nh; i++) {
        float ig = _sigmoid(gate[i]);                   /* input gate  */
        float fg = _sigmoid(gate[nh     + i]);          /* forget gate */
        float gg = tanhf   (gate[2 * nh + i]);          /* cell gate   */
        float og = _sigmoid(gate[3 * nh + i]);          /* output gate */
        c[i] = fg * c[i] + ig * gg;
        h[i] = og * tanhf(c[i]);
    }
}

/**
 * Fully-connected layer (matrix-vector multiply + bias).
 *
 * y = w @ x + b
 *
 * @param w   Weight matrix [out x in] row-major
 * @param b   Bias vector [out]
 * @param x   Input vector [in]
 * @param y   Output vector [out] — written in-place
 * @param out Output dimension
 * @param in  Input dimension
 */
static void _fc(
    const float *w, const float *b,
    const float *x, float *y,
    int out, int in)
{
    for (int i = 0; i < out; i++) {
        float v = b[i];
        const float *row = w + i * in;
        for (int j = 0; j < in; j++) v += row[j] * x[j];
        y[i] = v;
    }
}

/* ── Public API ───────────────────────────────────────────────────────────── */

float synera_infer(const float input[SYNERA_SEQ_LEN][SYNERA_FEATURES])
{
    /* ── ENCODER ─────────────────────────────────────────────────────────── */

    float h_enc[SYNERA_HIDDEN_SIZE];
    float c_enc[SYNERA_HIDDEN_SIZE];
    memset(h_enc, 0, sizeof(h_enc));
    memset(c_enc, 0, sizeof(c_enc));

    for (int t = 0; t < SYNERA_SEQ_LEN; t++) {
        _lstm_step(
            input[t],              SYNERA_FEATURES,
            h_enc, c_enc,
            &enc_lstm_wih[0][0],   /* [64][5]  */
            &enc_lstm_whh[0][0],   /* [64][16] */
            enc_lstm_bih,          /* [64]     */
            enc_lstm_bhh,          /* [64]     */
            SYNERA_HIDDEN_SIZE
        );
    }

    /* Latent projection: Linear(16 → 8) */
    float latent[SYNERA_LATENT_SIZE];
    _fc(&enc_fc_w[0][0], enc_fc_b, h_enc, latent,
        SYNERA_LATENT_SIZE, SYNERA_HIDDEN_SIZE);

    /* ── DECODER ─────────────────────────────────────────────────────────── */

    /* Expand latent: Linear(8 → 16) — same input tiled across all timesteps */
    float expanded[SYNERA_HIDDEN_SIZE];
    _fc(&dec_exp_w[0][0], dec_exp_b, latent, expanded,
        SYNERA_HIDDEN_SIZE, SYNERA_LATENT_SIZE);

    float h_dec[SYNERA_HIDDEN_SIZE];
    float c_dec[SYNERA_HIDDEN_SIZE];
    memset(h_dec, 0, sizeof(h_dec));
    memset(c_dec, 0, sizeof(c_dec));

    float mse = 0.0f;

    for (int t = 0; t < SYNERA_SEQ_LEN; t++) {
        /* Decoder LSTM step (same expanded latent each timestep) */
        _lstm_step(
            expanded,              SYNERA_HIDDEN_SIZE,
            h_dec, c_dec,
            &dec_lstm_wih[0][0],   /* [64][16] */
            &dec_lstm_whh[0][0],   /* [64][16] */
            dec_lstm_bih,          /* [64]     */
            dec_lstm_bhh,          /* [64]     */
            SYNERA_HIDDEN_SIZE
        );

        /* Output projection: Linear(16 → 5) + sigmoid */
        float out_t[SYNERA_FEATURES];
        _fc(&dec_out_w[0][0], dec_out_b, h_dec, out_t,
            SYNERA_FEATURES, SYNERA_HIDDEN_SIZE);

        /* Accumulate MSE while applying sigmoid */
        for (int j = 0; j < SYNERA_FEATURES; j++) {
            float recon = _sigmoid(out_t[j]);
            float diff  = input[t][j] - recon;
            mse += diff * diff;
        }
    }

    return mse / (float)(SYNERA_SEQ_LEN * SYNERA_FEATURES);
}

bool synera_is_anomaly(float mse)
{
    return mse > SYNERA_ANOMALY_THRESHOLD;
}
